import {
    s3,
    lambda,
    ses,
    sns,
    sqs,
    cloudformation,
    appsync,
    dynamodb,
    rds,
    neptune,
    cloudwatch,
    eventbridge,
    ec2,
    vpc,
    apigateway,
    iam,
    cognito,
    stepfunction,
    route53,
    cloudfront,
    codedeploy,
    amplify,
    pinpoint
} from '../../images/aws-pics';

export default  [
    {id: 1, name: "S3", detail: "Object Bucket", pic: s3},
    {id: 2, name: "LAMBDA", detail: "Serverless Function", pic: lambda},
    {id: 3, name: "SES", detail: "Simple Email Service", pic: ses},
    {id: 4, name: "SNS", detail: "Simple Notification Service", pic: sns},
    {id: 5, name: "SQS", detail: "Simple Queue Service",pic: sqs},
    {id: 6, name: "CLOUDFORMATION", detail: "Management Service", pic: cloudformation},
    {id: 7, name: "APPSYNC", detail: "GraphQL API", pic: appsync},
    {id: 8, name: "DYNAMODB", detail: "NoSQL Database", pic: dynamodb},
    {id: 9, name: "AURORASERVERLESS", detail: "SQL Database", pic: rds},
    {id: 10, name: "NEPTUNE", detail: "Graph Database", pic: neptune},
    {id: 11, name: "CLOUDWATCH", detail: "Monitoring Service", pic: cloudwatch},
    {id: 12, name: "EVENTBRIDGE", detail: "Serverless Event", pic: eventbridge},
    {id: 13, name: "EC2", detail: "EC2 Instance", pic: ec2},
    {id: 14, name: "VPC", detail: "Virtual Private Cloud", pic: vpc},
    {id: 15, name: "APIGATEWAY", detail: "Rest API", pic: apigateway},
    {id: 16, name: "IAM", detail: "IAMUser", pic: iam},
    {id: 17, name: "COGNITO", detail: "User Authentication", pic: cognito},
    {id: 18, name: "STEPFUNCTIONS", detail: "Step Functions", pic: stepfunction},
    {id: 19, name: "ROUTE53", detail: "Region Routes", pic: route53},
    {id: 20, name: "CLOUDFRONT", detail: "CloudFront", pic: cloudfront},
    {id: 21, name: "CODEDEPLOY", detail: "Code Deployment", pic: codedeploy},
    {id: 22, name: "AMPLIFY", detail: "Full Stack", pic: amplify},
    {id: 23, name: "PINPOINT", detail: "Messaging Notification", pic: pinpoint}
];