import {
    html,
    css,
    sass,
    js,
    ts,
    solidity,
    es6,
    react,
    next,
    gatsby,
    redux,
    zustand,
    pwa,
    nodejs,
    json,
    graphql,
    mern,
    jam,
    aws2,
    figma,
    contentful,
    bootstrap,
    tailwind,
    mui,
    styledcomponent,
    sql,
    gremlin,
    mysql,
    mssql,
    postgresql,
    mongodb,
    faunadb,
    vercel,
    netlify,
    firebase,
    testing
} from '../../images/services-pics';
import {
    s3,
    lambda,
    dynamodb,
    cognito,
    appsync,
    apigateway,
    amplify
} from '../../images/aws-pics';

export default [
    { id: 0, name: "HTML", detail: "Markup Language", pic: html },
    { id: 1, name: "CSS", detail: "StyleSheet Language", pic: css },
    { id: 2, name: "SASS", detail: "CSS Preprocessor", pic: sass },
    { id: 3, name: "JAVASCRIPT", detail: "Programming Language", pic: js },
    { id: 4, name: "TYPESCRIPT", detail: "Programming Language", pic: ts },
    { id: 5, name: "SOLIDITY", detail: "Programming Language", pic: solidity },
    { id: 6, name: "ECMASCRIPT", detail: "Advanced JavaScript", pic: es6 },
    { id: 7, name: "REACT JS", detail: "Frontend Library", pic: react },
    { id: 8, name: "REACT NATIVE", detail: "App Development", pic: react },
    { id: 9, name: "NEXT JS", detail: "ReactJS Framework", pic: next },
    { id: 10, name: "GATSBY JS", detail: "ReactJS Framework", pic: gatsby },
    { id: 11, name: "REDUX", detail: "State Managemnet", pic: redux },
    { id: 12, name: "CONTEXT", detail: "State Managemnet", pic: react },
    { id: 13, name: "ZUSTAND", detail: "State Managemnet", pic: zustand },
    { id: 14, name: "PWA", detail: "Progressive Web App", pic: pwa },
    { id: 15, name: "NODE JS", detail: "Backend Framework", pic: nodejs },
    { id: 16, name: "REST API", detail: "API Type", pic: json },
    { id: 18, name: "GRAPHQL", detail: "API Type", pic: graphql },
    { id: 19, name: "MERN STACK", detail: "Full Stack", pic: mern },
    { id: 20, name: "JAM STACK", detail: "Full Stack", pic: jam },
    { id: 21, name: "AWS", detail: "Amazon Web Services", pic: aws2 },
    { id: 22, name: "FIGMA", detail: "UI/UX Design", pic: figma },
    { id: 23, name: "CONTENTFUL", detail: "Headless CMS", pic: contentful },
    { id: 24, name: "BOOTSTRAP", detail: "CSS Framework", pic: bootstrap },
    { id: 25, name: "TAILWIND", detail: "CSS Framework", pic: tailwind },
    { id: 26, name: "MATERIAL UI", detail: "Style Library", pic: mui },
    { id: 27, name: "STYLED COMPONENT", detail: "Style Library", pic: styledcomponent },
    { id: 28, name: "SQL", detail: "Structured Query Language", pic: sql },
    { id: 29, name: "GREMLIN", detail: "Graph Query Language", pic: gremlin },
    { id: 30, name: "MYSQL", detail: "SQL Database", pic: mysql },
    { id: 31, name: "MSSQL", detail: "SQL Database", pic: mssql },
    { id: 32, name: "POSTGRESQL", detail: "SQL Database", pic: postgresql },
    { id: 33, name: "MONGODB", detail: "NoSQL Database", pic: mongodb },
    { id: 34, name: "FAUNADB", detail: "NoSQL Database", pic: faunadb },
    { id: 35, name: "FIRESTORE", detail: "NoSQL Database", pic: firebase },
    { id: 36, name: "VERCEL", detail: "Deloyment Platform", pic: vercel },
    { id: 37, name: "NETLIFY", detail: "Deloyment Platform", pic: netlify },
    { id: 38, name: "FIREBASE", detail: "Deloyment Platform", pic: firebase },
    { id: 39, name: "TESTING", detail: "Application Testing", pic: testing },
    { id: 40, name: "S3 ( AWS )", detail: "Object Bucket", pic: s3 },
    { id: 41, name: "LAMBDA ( AWS )", detail: "Serverless Function", pic: lambda },
    { id: 42, name: "DYNAMODB ( AWS )", detail: "NoSQL Database", pic: dynamodb },
    { id: 43, name: "COGNITO ( AWS )", detail: "User Authentication", pic: cognito },
    { id: 44, name: "APPSYNC ( AWS )", detail: "GraphQL API", pic: appsync },
    { id: 45, name: "APIGATEWAY ( AWS )", detail: "Rest API", pic: apigateway },
    { id: 46, name: "AMPLIFY ( AWS )", detail: "Full Stack", pic: amplify }
];