import {
    project0,
    /* FREELANCE */
    project21,
    project22,
    project23,
    project24,
    project25,
    /* FREELANCE */
    project1,
    project2,
    project3,
    project4a,
    project4b,
    project5,
    project6,
    project7a,
    project7b,
    project8,
    project9a,
    project9b,
    project10,
    project11,
    project12a,
    project12b,
    project12c,
    project12d,
    project13,
    project14,
    project15,
    project16,
    project17,
    project18,
    project19,
    project20
} from '../../images/projects-pics';

export default  [
    {id: 1, name: "Youtube Clone", technologies: "ReactJS <b>|</b> RouterDOM <b>|</b> Clone", url: "https://yotube-pwa.web.app", pic: project0},
    /* FREELANCE */
    {id: 21, name: "Haystack Steam", technologies: "NextJS <b>|</b> TailwindCSS <b>|</b> Typescript", url: "https://haystack.vercel.app", pic: project21},
    {id: 22, name: "Mifu Startup", technologies: "NextJS <b>|</b> TailwindCSS <b>|</b> Typescript", url: "https://mifu-landing-pages.vercel.app", pic: project22},
    {id: 23, name: "Dao Application", technologies: "ReactJS <b>|</b> TailwindCSS <b>|</b> Typescript", url: "https://dao-app.netlify.app", pic: project23},
    {id: 24, name: "Golove Dating", technologies: "NextJS <b>|</b> MaterialUI <b>|</b> Typescript", url: "https://golove.vercel.app", pic: project24},
    {id: 25, name: "Coinbull Pro", technologies: "GatsbyJS <b>|</b> MaterialUI <b>|</b> Typescript", url: "https://coinbullpro.netlify.app", pic: project25},
    /* FREELANCE */
    {id: 2, name: "Covid19 Tracker", technologies: "ReactJS <b>|</b> ChartJS <b>|</b> MaterialUI" , url: "https://covid19trackerapp-ali.netlify.app", pic: project2},
    {id: 3, name: "Shoes Store", technologies: "ReactJS <b>|</b> RouterDOM <b>|</b> Redux", url: "https://shoestoreapp-ali.netlify.app", pic: project3},
    {id: 4, name: "Simple Animation", technologies: "ReactJS <b>|</b> Animation <b>|</b> Graphics", url: "https://animationapp-ali.netlify.app", pic: project4a},
    {id: 5, name: "Web Animation", technologies: "ReactJS <b>|</b> Animation <b>|</b> Bootstrap", url: "https://webanimationapp-ali.netlify.app", pic: project4b},
    {id: 6, name: "New Animation", technologies: "ReactJS<b>|</b> Animation <b>|</b> MaterialUI", url: "https://newanimationapp-ali.netlify.app", pic: project5},
    {id: 7, name: "Quiz Application", technologies: "ReactJS <b>|</b> Typescript <b>|</b> MaterialUI", url: "https://quizapplicationapp-ali.netlify.app", pic: project6},
    {id: 8, name: "Timer Application", technologies: "ReactJS <b>|</b> Typescript <b>|</b> Testing", url: "https://timerapp-ali.netlify.app", pic: project7a},
    {id: 9, name: "Expense Tracker", technologies: "ReactJS <b>|</b> ContextAPI <b>|</b> Bootstrap", url: "https://expensetrackerapp-ali.netlify.app", pic: project1},
    {id: 10, name: "Expense Track PWA", technologies: "ReactJS <b>|</b> Typescript <b>|</b> PWA", url: "https://expensetracker-pwa.web.app", pic: project7b},
    {id: 11, name: "SpaceX Application", technologies: "ReactJS <b>|</b> GraphQL <b>|</b> MaterialUI", url: "https://spacexapp-ali.netlify.app", pic: project8},
    {id: 12, name: "Basket Application", technologies: "ReactJS <b>|</b> RouterDOM <b>|</b> Redux", url: "https://cricbasketapp-ali.netlify.app", pic: project9a},
    {id: 13, name: "Diary Application", technologies: "ReactJS <b>|</b> MirageJS <b>|</b> MaterialUI", url: "https://diaryapp-ali.netlify.app", pic: project9b},
    {id: 14, name: "Form Application", technologies: "ReactJS <b>|</b> Typescript <b>|</b> Formik", url: "https://formapp-ali.netlify.app", pic: project10},
    {id: 15, name: "Taskbox Application", technologies: "ReactJS <b>|</b> BitDev <b>|</b> Bootstrap", url: "https://taskboxapp-ali.netlify.app", pic: project11},
    {id: 16, name: "GatsbyJS Site", technologies: "GatsbyJS <b>|</b> Contentful <b>|</b> Netlify", url: "https://amazinggatsbyjssite.netlify.app", pic: project12a},
    {id: 17, name: "Serverless Crud", technologies: "GatsbyJS <b>|</b> FaunaDB <b>|</b> Netlify", url: "https://serverlesscrudapp-ali.netlify.app", pic: project12b},
    {id: 18, name: "Serverless Todo", technologies: "GatsbyJS <b>|</b> FaunaDB <b>|</b> Netlify", url: "https://serverlesstodoapp-ali.netlify.app", pic: project12c},
    {id: 19, name: "Bookmark Application", technologies: "GatsbyJS <b>|</b> FaunaDB <b>|</b> Netlify", url: "https://bookmarkapp-ali.netlify.app", pic: project12d},
    {id: 20, name: "Chat Application", technologies: "GatsbyJS <b>|</b> GraphQL <b>|</b> ContextAPI", url: "https://chatapp-ali.netlify.app", pic: project13},
    {id: 21, name: "Dinning Application", technologies: "GatsbyJS <b>|</b> GraphQL <b>|</b> AWS", url: "https://dinningapp-ali.netlify.app", pic: project14},
    {id: 22, name: "Pokemon PWA", technologies: "ReactJS <b>|</b> PWA <b>|</b> Firebase", url: "https://pokemon-pwa-e6b6e.web.app", pic: project15},
    {id: 23, name: "Google Clone", technologies: "ReactJS <b>|</b> RouterDOM <b>|</b> Clone", url: "https://googlapp-ali.web.app", pic: project16},
    {id: 24, name: "Netflix Clone", technologies: "ReactJS <b>|</b> Axios <b>|</b> Clone", url: "https://netflxapp-ali.web.app", pic: project17},
    {id: 25, name: "Meetups MongoDB", technologies: "NextJS <b>|</b> MongoDB <b>|</b> Vercel", url: "https://meetupsapp-mongodb.vercel.app", pic: project18},
    {id: 26, name: "Meetups FaunaDB", technologies: "NextJS <b>|</b> FaunaDB <b>|</b> Vercel", url: "https://meetupsapp-faunadb.vercel.app", pic: project19},
    {id: 27, name: "World Ranks PWA", technologies: "NextJS <b>|</b> PWA <b>|</b> Vercel", url: "https://worldranks-pwa.vercel.app", pic: project20}
];